[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clickcrate = "zLTwC7jeA9miBYVxzbTmDzEMXTobXQ3nxD8BY6M29nF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ap/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
